Repository PaddleHQ/paddle-php-sdk, pull requests merged in 2024-12, with the labels that each got.

#104 fix: Notification replay now calls correct endpoint
  CHANGELOG.md
  examples/notification_replay.php
  src/Resources/Notifications/NotificationsClient.php
  tests/Functional/Resources/Notifications/NotificationsClientTest.php
Labels: norelease

#103 feat: Add support for customer portal sessions
  CHANGELOG.md
  examples/customer_portal_session.php
  src/Client.php
  src/Entities/CustomerPortalSession.php
  src/Entities/CustomerPortalSession/CustomerPortalSessionGeneralUrl.php
  src/Entities/CustomerPortalSession/CustomerPortalSessionSubscriptionUrl.php
  src/Entities/CustomerPortalSession/CustomerPortalSessionUrls.php
  src/Resources/CustomerPortalSessions/CustomerPortalSessionsClient.php
  src/Resources/CustomerPortalSessions/Operations/CreateCustomerPortalSession.php
  tests/Functional/Resources/CustomerPortalSessions/CustomerPortalSessionsClientTest.php
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_empty.json
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_multiple.json
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/request/create_single.json
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_empty.json
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_multiple.json
  tests/Functional/Resources/CustomerPortalSessions/_fixtures/response/full_entity_single.json
Labels: norelease

#106 docs: Release 1.6.0
  CHANGELOG.md
  src/Client.php
Labels: release:minor

#108 Feat: Adding support for adjustment type and VND currency
  CHANGELOG.md
  src/Client.php
  src/Entities/Adjustment.php
  src/Entities/Adjustment/AdjustmentType.php
  src/Entities/Shared/CurrencyCode.php
  src/Notifications/Entities/Adjustment.php
  src/Notifications/Entities/Adjustment/AdjustmentType.php
  src/Notifications/Entities/Shared/CurrencyCode.php
  src/Resources/Adjustments/Operations/CreateAdjustment.php
  tests/Functional/Resources/Adjustments/_fixtures/response/full_entity.json
  tests/Functional/Resources/Adjustments/_fixtures/response/list_default.json
  tests/Functional/Resources/Adjustments/_fixtures/response/minimal_entity.json
  tests/Functional/Resources/Simulations/_fixtures/request/adjustment_updated_payload.json
  tests/Functional/Resources/Simulations/_fixtures/request/update_full.json
  tests/Functional/Resources/Simulations/_fixtures/response/full_entity_adjustment_updated.json
Labels: release:minor

#109 fix: Subscription discount now supports null starts_at
  CHANGELOG.md
  src/Client.php
  src/Entities/Subscription/SubscriptionDiscount.php
  src/Notifications/Entities/Subscription/SubscriptionDiscount.php
  tests/Functional/Resources/Subscriptions/_fixtures/response/list_default.json
  tests/Unit/Entities/EventTest.php
  tests/Unit/Entities/_fixtures/notification/entity/subscription.activated.json
  tests/Unit/Entities/_fixtures/notification/entity/subscription.canceled.json
Labels: release:patch

#110 fix: Adjustment items can be omitted when adjustment type is full
  CHANGELOG.md
  examples/adjustments.php
  src/Client.php
  src/Resources/Adjustments/Operations/CreateAdjustment.php
  tests/Functional/Resources/Adjustments/AdjustmentsClientTest.php
  tests/Functional/Resources/Adjustments/_fixtures/request/create_type_full_with_no_items.json
  tests/Functional/Resources/Adjustments/_fixtures/request/create_type_full_with_null_items.json
  tests/Functional/Resources/Adjustments/_fixtures/request/create_type_partial_with_items.json
  tests/Unit/Resources/Adjustments/Operations/CreateAdjustmentTest.php
Labels: release:patch
