Repository PaddleHQ/paddle-php-sdk, pull requests merged in 2024-09, with the labels that each got.

#63 Feature: Add product to subscription.items
  CHANGELOG.md
  src/Entities/Subscription/SubscriptionItem.php
  src/Notifications/Entities/Subscription/SubscriptionItem.php
  tests/Functional/Resources/Events/EventsClientTest.php
  tests/Functional/Resources/Events/_fixtures/response/list_default.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/full_entity_with_includes.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/list_default.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/preview_update_full_entity.json
Labels: norelease

#64 Feature: Add import_meta to transaction
  CHANGELOG.md
  src/Entities/Transaction.php
  tests/Functional/Resources/Subscriptions/SubscriptionsClientTest.php
  tests/Functional/Resources/Subscriptions/_fixtures/response/get_payment_method_change_transaction_entity_with_import_meta.json
  tests/Functional/Resources/Transactions/TransactionsClientTest.php
  tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_import_meta.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
Labels: norelease

#66 Fix README badges - use https
  README.md
Labels: norelease

#71 Feature: Support for createdAt and updatedAt on Subscription notification prices
  CHANGELOG.md
  src/Notifications/Entities/Subscription/SubscriptionPrice.php
  tests/Functional/Resources/Events/EventsClientTest.php
  tests/Functional/Resources/Events/_fixtures/response/list_default.json
  tests/Functional/Resources/Notifications/_fixtures/response/list_default.json
Labels: norelease

#76 fix: Remove import_meta from transaction
  CHANGELOG.md
  src/Entities/Transaction.php
  tests/Functional/Resources/Subscriptions/SubscriptionsClientTest.php
  tests/Functional/Resources/Subscriptions/_fixtures/response/get_payment_method_change_transaction_entity_with_import_meta.json
  tests/Functional/Resources/Transactions/TransactionsClientTest.php
  tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_import_meta.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
Labels: norelease

#77 `payment_method_id` can be `string` or `null`
  src/Entities/Shared/TransactionPaymentAttempt.php
Labels: norelease

#78 fix: Add test coverage and CHANGELOG for nullable `payment_method_id`
  CHANGELOG.md
  src/Entities/Shared/TransactionPaymentAttempt.php
  tests/Functional/Resources/Events/_fixtures/response/list_default.json
  tests/Functional/Resources/Transactions/TransactionsClientTest.php
  tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
Labels: norelease

#79 docs(release): v1.2.0
  CHANGELOG.md
  UPGRADING.md
  src/Client.php
Labels: release:minor

#81 feat: Add support for Adjustment Credit Note
  CHANGELOG.md
  src/Entities/AdjustmentCreditNote.php
  src/Resources/Adjustments/AdjustmentsClient.php
  src/Resources/Adjustments/Operations/GetAdjustmentCreditNote.php
  tests/Functional/Resources/Adjustments/AdjustmentsClientTest.php
  tests/Functional/Resources/Adjustments/_fixtures/response/get_credit_note_default.json
Labels: release:minor

#82 fix: Reference released version 1.3.1
  CHANGELOG.md
  src/Client.php
Labels: release:patch
