Repository PaddleHQ/paddle-php-sdk, pull requests merged in 2024-01, with the labels that each got.

#2 Fixing readme badges
  README.md
Labels: release:none, team-dx

#4 fix: Prevents invalid stream for null payloads
  CHANGELOG.md
  src/Client.php
Labels: release:patch

#6 Removal of php-http/message-factory
  composer.json
Labels: release:none

#7 Sync API spec with SDK
  CHANGELOG.md
  src/Client.php
  src/Entities/Address.php
  src/Entities/Business.php
  src/Entities/Customer.php
  src/Entities/Discount.php
  src/Entities/Price.php
  src/Entities/Product.php
  src/Entities/Shared/ImportMeta.php
  src/Entities/Shared/TransactionPayoutTotals.php
  src/Entities/Shared/TransactionTotals.php
  src/Entities/Subscription.php
  src/Entities/TransactionWithIncludes.php
  src/Resources/Customers/Operations/ListCustomers.php
  src/Resources/Transactions/Operations/List/Includes.php
  src/Resources/Transactions/Operations/List/Origin.php
  src/Resources/Transactions/Operations/ListTransactions.php
  tests/Functional/Resources/Customers/CustomersClientTest.php
  tests/Functional/Resources/Notifications/_fixtures/response/list_default.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/get_payment_method_change_transaction_entity.json
  tests/Functional/Resources/Subscriptions/_fixtures/response/preview_update_full_entity.json
  tests/Functional/Resources/Transactions/TransactionsClientTest.php
  tests/Functional/Resources/Transactions/_fixtures/response/full_entity.json
  tests/Functional/Resources/Transactions/_fixtures/response/full_entity_with_includes.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_default.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_one.json
  tests/Functional/Resources/Transactions/_fixtures/response/list_paginated_page_two.json
  tests/Functional/Resources/Transactions/_fixtures/response/minimal_entity.json
  tests/Functional/Resources/Transactions/_fixtures/response/preview_entity.json
Labels: release:minor

#8 docs: Update README.md for 0.2.0
  README.md
Labels: release:none

#14 Fix list notifications test case in NotificationsClientTest.php
  tests/Functional/Resources/Notifications/NotificationsClientTest.php
Labels: release:none

#13 Added Symfony 7 support
  composer.json
Labels: release:none
